"""
This type stub file was generated by pyright.
"""

from django.db.models import Model

class BaseLocation(Model):
    """Abstract base model for location entities."""
    name = ...
    code = ...
    def __str__(self) -> str:
        ...
    
    class Meta:
        abstract = ...
        ordering = ...
        indexes = ...
    
    


