"""
This type stub file was generated by pyright.
"""

from typing import Any
from django.db import models

class ProvinceField(models.ForeignKey):
    """A ForeignKey field for Iranian Provinces."""
    description: str = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    


class CountyField(models.ForeignKey):
    """A ForeignKey field for Iranian Counties."""
    description: str = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    


class DistrictField(models.ForeignKey):
    """A ForeignKey field for Iranian Districts."""
    description: str = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    


class CityField(models.ForeignKey):
    """A ForeignKey field for Iranian Cities."""
    description: str = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    


class RuralDistrictField(models.ForeignKey):
    """A ForeignKey field for Iranian Rural Districts."""
    description: str = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    


class VillageField(models.ForeignKey):
    """A ForeignKey field for Iranian Villages."""
    description: str = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    


