# Generated by Django 4.2.6 on 2026-06-12 14:33

import ckeditor.fields
import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Product Name')),
                ('title_fa', models.CharField(max_length=300, null=True, verbose_name='Product Name')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Product Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='Product image')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('short_description', models.CharField(db_index=True, max_length=400, null=True, verbose_name='Short Description')),
                ('short_description_fa', models.CharField(db_index=True, max_length=400, null=True, verbose_name='Short Description')),
                ('short_description_en', models.CharField(db_index=True, max_length=400, null=True, verbose_name='Short Description')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Main Description')),
                ('description_fa', ckeditor.fields.RichTextField(null=True, verbose_name='Main Description')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Main Description')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='discount percent')),
                ('discounted_price', models.IntegerField(blank=True, null=True, verbose_name='Price After Discount')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Title in url')),
                ('slug_fa', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url')),
                ('slug_en', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Width')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Length')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height')),
                ('warranty', models.IntegerField(blank=True, help_text='The amount you enter should be in months', null=True, verbose_name='warranty')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Weight')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='stock')),
                ('promotional', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('New', 'New'), ('Hot', 'Hot')], default='New', max_length=13, null=True, verbose_name='Promotional')),
                ('is_active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False, verbose_name='Status')),
                ('is_delete', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='This product will be removed from the website page, but it will be stored in the database', verbose_name='Delete')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='product_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Brand Title')),
                ('title_fa', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Brand Title')),
                ('title_en', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Brand Title')),
                ('url_title', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Title in url')),
                ('url_title_fa', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url')),
                ('url_title_en', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url')),
                ('is_active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Category Tile')),
                ('title_fa', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Category Tile')),
                ('title_en', models.CharField(db_index=True, max_length=300, null=True, verbose_name='Category Tile')),
                ('url_title', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Title in url')),
                ('url_title_fa', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url')),
                ('url_title_en', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url')),
                ('is_active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False, verbose_name='Status')),
                ('is_delete', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='This category will be removed from the website page, but it will be stored in the database', verbose_name='Delete')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Color Name')),
                ('name_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Color Name')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Color Name')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'White'), ('#000000', 'Black'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#FFC0CB', 'Pink'), ('#FF0000', 'Red'), ('#008000', 'Green'), ('#1E90FF', 'Indigo'), ('#0000FF', 'Blue'), ('#800080', 'Purple')])),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='ProductVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='User IP')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Product Visit',
                'verbose_name_plural': 'Product Visits',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=300, verbose_name='Product Tag Title')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product.product', verbose_name='Available product')),
            ],
            options={
                'verbose_name': 'Product Tag',
                'verbose_name_plural': 'Product Tags',
            },
        ),
        migrations.CreateModel(
            name='ProductPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strong_point', models.CharField(help_text='The maximum length is 200 character', max_length=200, verbose_name='Strong_Point')),
                ('strong_point_fa', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Strong_Point')),
                ('strong_point_en', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Strong_Point')),
                ('weak_point', models.CharField(help_text='The maximum length is 200 character', max_length=200, verbose_name='Weak_Point')),
                ('weak_point_fa', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Weak_Point')),
                ('weak_point_en', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Weak_Point')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_point', to='product.product', verbose_name='Available product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product-gallery', verbose_name='Product Image')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_brand', verbose_name='Brands'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_categories', to='product.productcategory', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='product_colors', to='product.productcolor', verbose_name='Colors'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
