# Generated by Django 5.0.2 on 2024-02-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name=' تخفبف  ')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(max_length=500, null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name=' درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True, verbose_name=' قیمت بعد از تخفیف '),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(db_index=True, max_length=400, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_fa',
            field=models.CharField(db_index=True, max_length=400, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name=' عنوان در url  '),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name=' عنوان در url  '),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name=' نام محصول '),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name=' نام محصول '),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='url_title_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name=' عنوان در url  '),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='url_title_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name=' عنوان در url  '),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, verbose_name='توضیحات اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, verbose_name=' وضعیت '),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], help_text='این محصول از صفحه وبسایت حذف شود ولی در دیتابیس ذخیره می ماند', verbose_name='  حذف  '),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(db_index=True, max_length=400, null=True, verbose_name='توضیحات کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name=' عنوان در url  '),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name=' عنوان در url  '),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name=' عنوان در url  '),
        ),
    ]
