# Generated by Django 5.0.2 on 2024-02-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_discount_product_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, help_text='این محصول از صفحه وبسایت حذف شود ولی در دیتابیس ذخیره می ماند', verbose_name='  حذف  '),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, verbose_name=' وضعیت '),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_delete',
            field=models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, help_text='این محصول از صفحه وبسایت حذف شود ولی در دیتابیس ذخیره می ماند', verbose_name='  حذف  '),
        ),
    ]
