# Generated by Django 5.0.2 on 2024-02-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'فعال'), (False, 'غیر فعال')], default=False, verbose_name=' وضعیت '),
        ),
    ]
