# Generated by Django 5.0.2 on 2024-02-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productcategory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='is_delete',
            field=models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, help_text='این دسته بندی از صفحه وبسایت حذف شود ولی در دیتابیس ذخیره می ماند', verbose_name='  حذف  '),
        ),
    ]
