# Generated by Django 5.0.2 on 2024-02-29 15:54

import ckeditor.fields
import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productcategory_is_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Color Name')),
                ('name_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Color Name')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Color Name')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'White'), ('#000000', 'Black'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#FFC0CB', 'Pink'), ('#FF0000', 'Red'), ('#008000', 'Green'), ('#1E90FF', 'Indigo'), ('#0000FF', 'Blue'), ('#800080', 'Purple')])),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='ProductPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strong_point', models.CharField(help_text='The maximum length is 200 character', max_length=200, verbose_name='Strong_Point')),
                ('strong_point_fa', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Strong_Point')),
                ('strong_point_en', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Strong_Point')),
                ('weak_point', models.CharField(help_text='The maximum length is 200 character', max_length=200, verbose_name='Weak_Point')),
                ('weak_point_fa', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Weak_Point')),
                ('weak_point_en', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Weak_Point')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='product_brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name': 'Product Tag', 'verbose_name_plural': 'Product Tags'},
        ),
        migrations.AlterModelOptions(
            name='productvisit',
            options={'verbose_name': 'Product Visit', 'verbose_name_plural': 'Product Visits'},
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='product',
            name='promotional',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('New', 'New'), ('Hot', 'Hot')], default='New', max_length=13, null=True, verbose_name='Promotional'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, help_text='The amount you enter should be in months', null=True, verbose_name='warranty'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Width'),
        ),
        migrations.AddField(
            model_name='product_brand',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Brand Title'),
        ),
        migrations.AddField(
            model_name='product_brand',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Brand Title'),
        ),
        migrations.AddField(
            model_name='product_brand',
            name='url_title_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url'),
        ),
        migrations.AddField(
            model_name='product_brand',
            name='url_title_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_brand', verbose_name='Brands'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_categories', to='product.productcategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Main Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Main Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fa',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Main Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='discount percent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price After Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='This product will be removed from the website page, but it will be stored in the database', verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(db_index=True, max_length=400, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(db_index=True, max_length=400, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description_fa',
            field=models.CharField(db_index=True, max_length=400, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Brand Title'),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_delete',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='This category will be removed from the website page, but it will be stored in the database', verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Category Tile'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Category Tile'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Category Tile'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='images/product-gallery', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='caption',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Product Tag Title'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product.product', verbose_name='Available product'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='User IP'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='product_colors', to='product.productcolor', verbose_name='Colors'),
        ),
        migrations.AddField(
            model_name='productpoint',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_point', to='product.product', verbose_name='Available product'),
        ),
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.product'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'product')},
        ),
    ]
