# Generated by Django 5.0.2 on 2024-02-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productcategory_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_brand',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name=' نام برند '),
        ),
        migrations.AddField(
            model_name='product_brand',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name=' نام برند '),
        ),
        migrations.AddField(
            model_name='product_brand',
            name='url_title_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name=' عنوان در url  '),
        ),
        migrations.AddField(
            model_name='product_brand',
            name='url_title_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name=' عنوان در url  '),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'فعال'), (False, 'غیر فعال')], default=False, verbose_name=' وضعیت '),
        ),
    ]
