# Generated by Django 5.0.2 on 2024-02-28 03:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_brand_title_en_product_brand_title_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fa',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات اصلی'),
        ),
    ]
