# Generated by Django 5.0.2 on 2024-02-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productcolor_productpoint_rating_delete_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='name_fa',
        ),
    ]
