# Generated by Django 5.0.2 on 2024-02-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='موجودی'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='ارتفاع'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='طول'),
        ),
        migrations.AddField(
            model_name='product',
            name='promotional',
            field=models.CharField(blank=True, choices=[('Normal', 'معمولی'), ('New', 'جدید'), ('Hot', 'داغ')], default='New', max_length=13, null=True, verbose_name='تبلیغاتی'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='تنظیم وزن بر حسب  گرم'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض'),
        ),
    ]
