# Generated by Django 5.0.2 on 2024-02-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_productcolor_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Color Name'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='name_fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Color Name'),
        ),
    ]
