# Generated by Django 5.0.2 on 2024-02-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_available_product_height_product_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(choices=[('Active', 'فعال'), ('Inactive', 'غیر فعال')], default=False, verbose_name=' وضعیت '),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='url_title_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url'),
        ),
    ]
