# Generated by Django 5.0.2 on 2024-02-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_delete',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, help_text='This category will be removed from the website page, but it will be stored in the database', verbose_name='Delete'),
        ),
    ]
