# Generated by Django 5.0.2 on 2024-02-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(choices=[('True', 'Active'), ('False', 'Inactive')], default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_delete',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=False, help_text='This category will be removed from the website page, but it will be stored in the database', verbose_name='Delete'),
        ),
    ]
