# Generated by Django 5.0.2 on 2024-02-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_productcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='This category will be removed from the website page, but it will be stored in the database', verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Brand Title'),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Brand Title'),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Brand Title'),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='url_title_en',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='product_brand',
            name='url_title_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Category Tile'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Category Tile'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Category Tile'),
        ),
    ]
