# Generated by Django 5.0.2 on 2024-02-28 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_delete_discount_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='product',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول'),
        ),
    ]
