# Generated by Django 5.0.2 on 2024-02-28 05:34

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_productgallery_product_productgallery_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name': 'Product Tag', 'verbose_name_plural': 'Product Tags'},
        ),
        migrations.AlterModelOptions(
            name='productvisit',
            options={'verbose_name': 'Product Visit', 'verbose_name_plural': 'Product Visits'},
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='This product will be removed from the website page, but it will be stored in the database', verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='images/product-gallery', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='caption',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Product Tag Title'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product.product', verbose_name='Available Tags'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='User IP'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
