# Generated by Django 5.0.2 on 2024-02-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_productcolor_remove_product_color_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Color Name'),
        ),
    ]
