# Generated by Django 5.0.2 on 2024-02-28 05:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_productcolor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FFFF00', 'yellow'), ('#FFA500', 'orange'), ('#FFC0CB', 'pink'), ('#FF0000', 'red')]),
        ),
    ]
