# Generated by Django 5.0.2 on 2024-02-28 06:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_productcolor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'White'), ('#000000', 'Black'), ('#FFFF00', 'Yellow'), ('#FFA500', 'Orange'), ('#FFC0CB', 'Pink'), ('#FF0000', 'Red'), ('#008000', 'Green'), ('#1E90FF', 'Indigo'), ('#0000FF', 'Blue'), ('#800080', 'Purple')]),
        ),
    ]
