# Generated by Django 5.0.2 on 2024-02-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_productcolor_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(blank=True, help_text='The amount you enter should be in months', null=True, verbose_name='warranty'),
        ),
    ]
