# Generated by Django 5.0.2 on 2024-02-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_product_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='product_colors', to='product.productcolor', verbose_name='Colors'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product.product', verbose_name='Available product'),
        ),
        migrations.CreateModel(
            name='ProductPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strong_point', models.CharField(help_text='The maximum length is 200 character', max_length=200, verbose_name='Strong_Point')),
                ('strong_point_fa', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Strong_Point')),
                ('strong_point_en', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Strong_Point')),
                ('weak_point', models.CharField(help_text='The maximum length is 200 character', max_length=200, verbose_name='Weak_Point')),
                ('weak_point_fa', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Weak_Point')),
                ('weak_point_en', models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Weak_Point')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_point', to='product.product', verbose_name='Available product')),
            ],
        ),
    ]
