# Generated by Django 5.0.2 on 2024-02-28 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_productpoint_alter_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='point',
        ),
        migrations.AddField(
            model_name='productpoint',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_point', to='product.product', verbose_name='Available product'),
        ),
        migrations.AddField(
            model_name='productpoint',
            name='strong_point_en',
            field=models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Strong_Point'),
        ),
        migrations.AddField(
            model_name='productpoint',
            name='strong_point_fa',
            field=models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Strong_Point'),
        ),
        migrations.AddField(
            model_name='productpoint',
            name='weak_point_en',
            field=models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Weak_Point'),
        ),
        migrations.AddField(
            model_name='productpoint',
            name='weak_point_fa',
            field=models.CharField(help_text='The maximum length is 200 character', max_length=200, null=True, verbose_name='Weak_Point'),
        ),
    ]
