# Generated by Django 4.2.6 on 2024-03-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productcolor_name_en_productcolor_name_fa'),
        ('product', '0032_rating'),
        ('product', '0032_remove_product_point_productpoint_product_and_more'),
    ]

    operations = [
    ]
