# Generated by Django 4.2.6 on 2026-06-12 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Article Title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, verbose_name='Title in url')),
                ('image', models.ImageField(upload_to='images/articles', verbose_name='Image of the Article')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('text', models.TextField(null=True, verbose_name='Article text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / Passive')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name=' Date of Registration')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='The Writer')),
            ],
            options={
                'verbose_name': ' Article',
                'verbose_name_plural': ' Articles ',
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name=' Date of Registration')),
                ('text', models.TextField(verbose_name='comment text ')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active / Passive')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='Article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.articlecomment', verbose_name=' parent ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'article comment',
                'verbose_name_plural': 'Article Comments',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Category Title')),
                ('url_title', models.CharField(max_length=200, unique=True, verbose_name='Title in url')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active / Passive')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.articlecategory', verbose_name='Subcategory')),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': ' Articles Categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='selected_categories',
            field=models.ManyToManyField(to='article.articlecategory', verbose_name='Categories'),
        ),
    ]
