# Generated by Django 4.2.6 on 2024-02-12 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0012_alter_articlecategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': ' Article', 'verbose_name_plural': ' Articles '},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Article Category', 'verbose_name_plural': ' Articles Categories'},
        ),
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'article comment', 'verbose_name_plural': 'Article Comments'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='The Writer'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' Date of Registration'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/articles', verbose_name='Image of the Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active / Passive'),
        ),
        migrations.AlterField(
            model_name='article',
            name='selected_categories',
            field=models.ManyToManyField(to='article.articlecategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=400, verbose_name='Title in url'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(null=True, verbose_name='Article text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Article Title'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active / Passive'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Category Title'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' Date of Registration'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active / Passive'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.articlecomment', verbose_name=' parent '),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=models.TextField(verbose_name='comment text '),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
