# Generated by Django 4.2.6 on 2024-01-26 22:11

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Proposal', 'پیشنهاد ها'), ('Criticism', ' انتقاد ها '), ('Complaint', ' شکایت '), ('Tracking', ' پیگیری سفارش '), ('other', ' سایر موارد ')], max_length=200, null=True, verbose_name=' موضوع')),
                ('title', models.CharField(max_length=300, verbose_name=' عنوان ')),
                ('full_name', models.CharField(max_length=300, verbose_name=' نام و نام خانوادگی ')),
                ('email', models.EmailField(max_length=300, verbose_name=' ایمیل ')),
                ('mobile_number', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0, message='شماره همراه باید 11 رقم باشد.'), django.core.validators.MaxLengthValidator(limit_value=99999999999, message='شماره همراه باید 11 رقم باشد.')], verbose_name='شماره همراه')),
                ('message', models.TextField(max_length=300, verbose_name=' متن تماس با ما ')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name=' تاریح ایجاد ')),
                ('response', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name=' متن پاسخ تماس با ما ')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name=' مشاهده شده توسط ادمین ')),
            ],
            options={
                'verbose_name': ' نماس با ما ',
                'verbose_name_plural': ' لیست تماس با ما ',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
