# Generated by Django 4.2.6 on 2026-06-12 14:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Proposal', 'Suggestions'), ('Criticism', 'Criticisms'), ('Complaint', ' Complaint '), ('Tracking', 'Order Tracking'), ('other', ' Other cases ')], max_length=200, null=True, verbose_name='Subject')),
                ('title', models.CharField(max_length=300, verbose_name=' Title ')),
                ('full_name', models.CharField(max_length=300, verbose_name=' First Name and Last Name ')),
                ('email', models.EmailField(max_length=300, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=11, null=True, verbose_name='Phone Number')),
                ('message', models.TextField(max_length=300, verbose_name='Text to Contact us')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name=' Creation Date ')),
                ('response', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer text')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='Viewed by Admin')),
            ],
            options={
                'verbose_name': ' Contact us ',
                'verbose_name_plural': 'Contacts us',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
