# Generated by Django 4.2.6 on 2024-01-26 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='mobile_number',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=0, message='شماره همراه باید 11 رقم باشد.'), django.core.validators.MaxLengthValidator(limit_value=99999999999, message='شماره همراه باید 11 رقم باشد.')], verbose_name='شماره همراه'),
        ),
    ]
