# Generated by Django 4.2.6 on 2024-01-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_us_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='mobile_number',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره همراه'),
        ),
    ]
