# Generated by Django 4.2.6 on 2024-02-12 16:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_us_mobile_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': ' Contact us ', 'verbose_name_plural': 'Contacts us'},
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name=' Creation Date '),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(max_length=300, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='full_name',
            field=models.CharField(max_length=300, verbose_name=' First Name and Last Name '),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='is_read_by_admin',
            field=models.BooleanField(default=False, verbose_name='Viewed by Admin'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.TextField(max_length=300, verbose_name='Text to Contact us'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='mobile_number',
            field=models.CharField(max_length=11, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='response',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Answer text'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='subject',
            field=models.CharField(choices=[('Proposal', 'Suggestions'), ('Criticism', 'Criticisms'), ('Complaint', ' Complaint '), ('Tracking', 'Order Tracking'), ('other', ' Other cases ')], max_length=200, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='title',
            field=models.CharField(max_length=300, verbose_name=' Title '),
        ),
    ]
