# Generated by Django 4.2.6 on 2026-06-12 14:33

import account.models
import account.validators
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(blank=True, db_index=True, help_text='فرمت معتبر: 09XXXXXXXXX', max_length=11, null=True, unique=True, validators=[account.validators.validate_iran_mobile], verbose_name='شماره موبایل')),
                ('national_code', models.CharField(blank=True, db_index=True, help_text='۱۰ رقم، با کنترل صحت', max_length=10, null=True, unique=True, validators=[account.validators.validate_iran_national_code], verbose_name='کد ملی')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=account.models.user_avatar_upload_path, verbose_name='تصویر پروفایل')),
                ('email_activation_code', models.CharField(blank=True, db_index=True, help_text='برای تأیید ایمیل یا بازیابی رمز عبور', max_length=128, null=True, verbose_name='کد فعال\u200cسازی ایمیل')),
                ('about_user', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('account_type', models.CharField(choices=[('customer', 'مشتری'), ('vendor', 'فروشنده')], db_index=True, default='customer', max_length=16, verbose_name='نوع حساب')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], db_index=True, max_length=16, null=True, verbose_name='جنسیت')),
                ('is_admitted', models.BooleanField(default=False, help_text='برای فروشندگان یا کاربران احراز هویت شده', verbose_name='پذیرفته/احراز شده')),
                ('job', models.CharField(blank=True, max_length=200, null=True, verbose_name='شغل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: خانه، محل کار', max_length=50, verbose_name='عنوان آدرس')),
                ('address_type', models.CharField(choices=[('shipping', 'آدرس ارسال'), ('billing', 'آدرس صورتحساب')], default='shipping', max_length=16, verbose_name='نوع آدرس')),
                ('province', models.CharField(db_index=True, max_length=50, verbose_name='استان')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='شهر')),
                ('address_line', models.TextField(help_text='خیابان، کوچه، پلاک، واحد', verbose_name='نشانی پستی')),
                ('postal_code', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='کد پستی باید ۱۰ رقم باشد.', regex='^\\d{10}$')], verbose_name='کد پستی')),
                ('receiver_full_name', models.CharField(max_length=100, verbose_name='نام گیرنده')),
                ('receiver_mobile', models.CharField(db_index=True, max_length=11, validators=[account.validators.validate_iran_mobile], verbose_name='موبایل گیرنده')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'indexes': [models.Index(fields=['user', 'is_default'], name='account_add_user_id_ee8e28_idx'), models.Index(fields=['province', 'city'], name='account_add_provinc_110bf2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['mobile'], name='account_use_mobile_6a0dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['national_code'], name='account_use_nationa_6b1fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_type'], name='account_use_account_72ad67_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['gender'], name='account_use_gender_faf63e_idx'),
        ),
    ]
