# Generated by Django 5.0.2 on 2024-02-26 14:33

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('iranian_cities', '0005_alter_abadi_amar_code_alter_dehestan_amar_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='about_user',
            field=models.TextField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name=' Address '),
        ),
        migrations.AddField(
            model_name='user',
            name='admission',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='admission'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile', verbose_name='Avatar image'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=' Date of birth '),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=iranian_cities.fields.ShahrestanField(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahrestan', verbose_name='City '),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'Man'), ('Female', 'Female')], default='-----', max_length=13, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(max_length=200, null=True, verbose_name=' Job'),
        ),
        migrations.AddField(
            model_name='user',
            name='legendry_code',
            field=models.CharField(max_length=20, null=True, verbose_name=' National Code '),
        ),
        migrations.AddField(
            model_name='user',
            name='post_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post code'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=iranian_cities.fields.OstanField(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan', verbose_name=' State'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('vendor', 'vendor')], default='customer', max_length=13, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(max_length=100, verbose_name='Email activation code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=20, null=True, verbose_name='Mobile number'),
        ),
    ]
