# Generated by Django 4.2.6 on 2024-01-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdetail',
            options={'verbose_name': 'جزئیات سبد خرید', 'verbose_name_plural': 'لیست جزئیات سبدهای خرید'},
        ),
        migrations.RenameField(
            model_name='cartdetail',
            old_name='order',
            new_name='cart',
        ),
    ]
