# Generated by Django 4.2.6 on 2024-01-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cartdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(blank=True, null=True, verbose_name='نهایی شده / نشده'),
        ),
    ]
